package server

import (
	"strings"
	"testing"
)

func TestRESPParserByTypes(t *testing.T) {

	testCases := []struct {
		name           string
		input          []byte
		expectedOutput RespValue
	}{
		{
			name:           "Test parsing simple string",
			input:          []byte("+hello redis this is a simple string\r\nstuff\r\n"),
			expectedOutput: RespValue{vtype: SIMPLE_STRING, str: "hello redis this is a simple string"},
		},
		{
			name:           "Test parsing error",
			input:          []byte("-ERR redis needs a break\r\nstuff\n\r"),
			expectedOutput: RespValue{vtype: ERROR, err: "ERR redis needs a break"},
		},
		{
			name:           "Test parsing integer",
			input:          []byte(":69\r\n+haha, nice\n\n\n"),
			expectedOutput: RespValue{vtype: INTEGER, num: 69},
		},
		{
			name:           "Test parsing bulk string",
			input:          []byte("$15\r\nHello, worldddd\r\naccidentallysummonedemmamyerswhatdoido?\r\r\r"),
			expectedOutput: RespValue{vtype: BULK_STRING, bulkStr: "Hello, worldddd"},
		},
		{
			name:  "Test parsing array",
			input: []byte("*5\r\n+this is generated by chatgpt\r\n+why would i write these by myself?\r\n:101\r\n-ERR diversity\r\n$10\r\n0123456789\r\n\r\n\r\nig"),
			expectedOutput: RespValue{
				vtype: ARRAY,
				array: []RespValue{
					{vtype: SIMPLE_STRING, str: "this is generated by chatgpt"},
					{vtype: SIMPLE_STRING, str: "why would i write these by myself?"},
					{vtype: INTEGER, num: 101},
					{vtype: ERROR, err: "ERR diversity"},
					{vtype: BULK_STRING, bulkStr: "0123456789"},
				},
			},
		},
	}

	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			resp := NewResp(strings.NewReader(string(testCase.input)))
			v, err := resp.Read()
			if err != nil {
				t.Error(err.Error())
			}
			if !v.Equal(testCase.expectedOutput) {
				t.Errorf("expected %s, got %s", testCase.expectedOutput.String(), v.String())
			}
		})
	}
}
